version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: orbit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orbit_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./orbit_backup.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: orbit_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/orbit_db
      - API_URL=http://localhost:8080
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orbit_frontend
    restart: always
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - BACKEND_URL=http://orbit_backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
